name: AndroidBuild
on:
  pull_request :
    branches : [ master]
  push :
      branches : [master]

jobs:
  build:
    runs-on : ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Setup Java JDK
        uses: actions/setup-java@v4.0.0
        with:
          java-version : '11'
          distribution: 'adopt'

      - name : Build with Gradle
        run : ./gradlew assembleDebug assembleAndroidTest

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm
          
      # - name: Launch emulator
      #   run: |
      #     emulator -avd avd-5544 -no-window &  # Replace with your AVD name
      #     sleep 120  # Adjust sleep time based on emulator startup
      #     ./gradlew connectedCheck
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Pull emulator image
        run: docker pull android-emulator
      - name: Start emulator (adjust port if needed)
        run: docker run -d -p 5555:5555 android-emulator emualdor @my_avd -no-window
      - name: Run tests (use `adb devices` to verify connection)
        run: ./gradlew connectedCheck

      - name: Run tests
        run: ./gradlew connectedCheck

      - name: UI Test
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          target: default
          arch: x86
          profile: Nexus 6
          script: ./gradlew connectedCheck --stacktrace
      

      - name: Unit Test
        run: ./gradlew testDebugUnitTest
      - name: Android Test Report
        uses: holybear/android-test-report-action@v1.0.0
        if: ${{ always() }}

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.1.0
        with:
          name: EduFileShare.apk
          path: app/build/outputs/apk/debug/app-debug.apk



