name: AndroidBuild
on:
  pull_request :
    branches : [ master]
  push :
      branches : [master]

jobs:
  build:
    runs-on : ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Setup Java JDK
        uses: actions/setup-java@v4.0.0
        with:
          java-version : '11'
          distribution: 'adopt'

      - name : Build with Gradle
        run : ./gradlew build assembleAndroidTest

      - name: Run tests
        uses: MarathonLabs/action-test@0.3.0
        with:
            apiKey: ${{ secrets.MARATHON }}
            application: app/build/outputs/apk/debug/app-debug.apk
            platform: Android
            githubToken: ${{ secrets.GIT_TOKEN }}

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.1.0
        with:
          name: EduFileShare.apk
          path: app/build/outputs/apk/debug/app-debug.apk



